services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgressql/data
    healthcheck:
      test: ["CMD-SHELL" , "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api: 
    build: 
      context: .
      dockerfile: src/docker/dockerFile.api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment: 
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET : ${JWT_SECRET}
      NODE_ENV : production
      PORT : 3000
    depends_on:
      postgres:
        condition: service_healthy

  worker: 
    build: 
      context: .
      dockerfile: src/docker/dockerFile.worker
    restart: unless-stopped
    environment: 
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      NODE_ENV : production
    depends_on:
      postgres:
        condition: service_healthy
      api:                        
        condition: service_started 
volumes:
  pgdata: