name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # only on main branch

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1081146199416/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@webhook-pipeline-prod-491111.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push API image
        run: |
          docker build -f docker/Dockerfile.api \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/webhook-pipeline/api:${{ github.sha }} \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/webhook-pipeline/api:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/webhook-pipeline/api:${{ github.sha }}
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/webhook-pipeline/api:latest

      - name: Build and push Worker image
        run: |
          docker build -f docker/Dockerfile.worker \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/webhook-pipeline/worker:${{ github.sha }} \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/webhook-pipeline/worker:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/webhook-pipeline/worker:${{ github.sha }}
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/webhook-pipeline/worker:latest

      - name: Deploy API to Cloud Run
        run: |
          gcloud run deploy webhook-pipeline-api \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/webhook-pipeline/api:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

      - name: Deploy Worker to Cloud Run
        run: |
          gcloud run deploy webhook-pipeline-worker \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/webhook-pipeline/worker:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --min-instances=1
